apiVersion: v1
kind: Secret
metadata:
  name: strapi-db-secret
  labels:
    {{- include "strapi.labels" . | nindent 4 }}
stringData:
  DATABASE_HOST: {{.Values.db.host}}
  DATABASE_PASSWORD: {{.Values.db.pass}}
  DATABASE_USERNAME: {{.Values.db.username}}