apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strapi-volume-claim
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.scName }}