{{- with .Values.storage.nfs }} 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: strapi-volume
spec:
  capacity:
    storage: {{ $.Values.storage.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ $.Values.storage.accessMode }}
  nfs:
    path: {{.path}}
    server: {{.server}}
{{- end }}